[package]
name = "pallet-offences-benchmarking"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME offences pallet benchmarking"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }

frame-benchmarking = { version = "2.0.0-dev", default-features = false, path = "../../benchmarking" }
frame-support = { version = "2.0.0-dev", default-features = false, path = "../../support" }
frame-system = { version = "2.0.0-dev", default-features = false, path = "../../system" }
pallet-balances = { version = "2.0.0-dev", path = "../../balances" }
pallet-im-online = { version = "2.0.0-dev", default-features = false, path = "../../im-online" }
pallet-offences = { version = "2.0.0-dev", default-features = false, features = ["runtime-benchmarks"], path = "../../offences" }
pallet-session = { version = "2.0.0-dev", default-features = false, path = "../../session" }
pallet-staking = { version = "2.0.0-dev", default-features = false, features = ["runtime-benchmarks"], path = "../../staking" }
sp-io = { path = "../../../primitives/io", default-features = false, version = "2.0.0-dev"}
sp-runtime = { version = "2.0.0-dev", default-features = false, path = "../../../primitives/runtime" }
sp-staking = { version = "2.0.0-dev", default-features = false, path = "../../../primitives/staking" }
sp-std = { version = "2.0.0-dev", default-features = false, path = "../../../primitives/std" }

[dev-dependencies]
serde = { version = "1.0.101" }
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
sp-core = { version = "2.0.0-dev", path = "../../../primitives/core" }
pallet-staking-reward-curve = { version = "2.0.0-dev", path = "../../staking/reward-curve" }
sp-io ={ path = "../../../primitives/io", version = "2.0.0-dev"}
pallet-timestamp = { version = "2.0.0-dev", path = "../../timestamp" }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-std/std",
	"sp-staking/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-offences/std",
	"pallet-im-online/std",
	"pallet-staking/std",
	"pallet-session/std",
]
